#!/bin/sh
#
# extract states of module

die () {
  echo "*** usage: states <module>.c" 1>&2
  exit 1
}

[ $# = 1 ] || die
module=`basename "$1" .c`
[ "$module".c = "$1" ] || die

src=$module.c
dst=$module.states

echo "extracting states from $src into $dst"

rm -f $dst || exit 1
grep -v 'include <' $src | 
grep -v 'include ".*.states"' $src | 
cpp | \
grep 'static ' |
grep ';' | \
grep -v '{' |
tr \; \\n | \
sed \
  -e '/^[	]*$/d' \
  -e 's,\[.*\],,g' \
  -e 's,[\*]*,,g' \
| awk '{print "STATEMACRO(" $NF ");"}' \
> $dst
